# Generated by Django 4.2.1 on 2023-05-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penagos_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fortnite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('plataforma', models.CharField(max_length=100)),
                ('lanzamiento', models.DateField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ResidentEvil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('plataforma', models.CharField(max_length=100)),
                ('lanzamiento', models.DateField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Videojuegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('plataforma', models.CharField(max_length=50)),
                ('lanzamiento', models.DateField()),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
