# Generated by Django 4.2.1 on 2023-05-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penagos_app', '0002_fortnite_residentevil_videojuegos'),
    ]

    operations = [
        migrations.AddField(
            model_name='palabra',
            name='respuesta',
            field=models.CharField(default='valor predeterminado', max_length=100),
        ),
    ]
