# Generated by Django 4.2.1 on 2023-06-01 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('penagos_app', '0003_palabra_respuesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarioBros',
            fields=[
                ('videojuegos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='penagos_app.videojuegos')),
                ('compatatibilidad', models.CharField(max_length=100)),
            ],
            bases=('penagos_app.videojuegos',),
        ),
        migrations.CreateModel(
            name='Spiderman',
            fields=[
                ('videojuegos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='penagos_app.videojuegos')),
                ('compatatibilidad', models.CharField(max_length=100)),
            ],
            bases=('penagos_app.videojuegos',),
        ),
    ]
