# Generated by Django 4.2.1 on 2023-06-01 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penagos_app', '0004_mariobros_spiderman'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mariobros',
            old_name='compatatibilidad',
            new_name='compatibilidad',
        ),
        migrations.RenameField(
            model_name='spiderman',
            old_name='compatatibilidad',
            new_name='compatibilidad',
        ),
    ]
