# Generated by Django 4.2.1 on 2023-06-01 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penagos_app', '0005_rename_compatatibilidad_mariobros_compatibilidad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mariobros',
            options={'default_related_name': 'mariobros'},
        ),
    ]
