# Generated by Django 4.2.1 on 2023-06-01 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('penagos_app', '0006_alter_mariobros_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mariobros',
            name='videojuegos_ptr',
        ),
        migrations.RemoveField(
            model_name='spiderman',
            name='videojuegos_ptr',
        ),
        migrations.AddField(
            model_name='mariobros',
            name='videojuego_mariobros',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='penagos_app.videojuegos'),
        ),
        migrations.AddField(
            model_name='spiderman',
            name='videojuego_spiderman',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='penagos_app.videojuegos'),
        ),
    ]
