# Generated by Django 4.2.1 on 2023-06-01 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penagos_app', '0007_remove_mariobros_videojuegos_ptr_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spiderman',
            options={'default_related_name': 'spiderman'},
        ),
        migrations.RenameField(
            model_name='mariobros',
            old_name='videojuego_mariobros',
            new_name='videojuegos_ptr',
        ),
        migrations.RenameField(
            model_name='spiderman',
            old_name='videojuego_spiderman',
            new_name='videojuegos_ptr',
        ),
    ]
