# Generated by Django 4.2.1 on 2023-06-01 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penagos_app', '0008_alter_spiderman_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spiderman',
            name='videojuegos_ptr',
        ),
        migrations.DeleteModel(
            name='MarioBros',
        ),
        migrations.DeleteModel(
            name='Spiderman',
        ),
    ]
